### ISSUE TITLE
BetterShop Items

### ISSUE THREAD

**Issue by ghost** [HcRaid-Old/old#2]
@HcRaid-Old , Can we get the shop item list CSV file? Thanks!
-Hidden

**Comment by HcRaid-Old** [comment]
I have deleted all my backups of the server, bar mini-games. But that doesn't contain the bettershop plugin or csv.

**Comment by ghost** [comment]
Ah alright. Thanks anyways! :P

**Comment by HcRaid-Old** [comment]
Think I found some old versions of BetterShop - added to repo
